FROM postgres:15

RUN apt-get update \
    && apt-get install -y git build-essential postgresql-server-dev-15 \
    && rm -rf /var/lib/apt/lists/*

RUN cd /tmp \
    && git clone --branch v0.4.4 https://github.com/pgvector/pgvector.git \
    && cd pgvector \
    && make \
    && make install
