version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    # release.sh runs migrations, collects static files, and starts the server
    command: sh /code/release.sh
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"


volumes:
  postgres_data:
