# Generated by Django 4.2.10 on 2024-02-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('hobby', 'Hobby'), ('paid', 'Paid')], default='free', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
    ]
