# Generated by Django 4.2.10 on 2024-02-20 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overmail', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailWebhook',
        ),
    ]
